### ISSUE TITLE
Several tracebacks

### ISSUE THREAD

**Issue by quozl** [sugarlabs/Bichos#2]
```log
Corriendo Intro . . .
Corriendo CucaraSims . . .
Traceback (most recent call last):
  File "/home/olpc/Activities/Bichos.activity/CucaraSims/Widgets.py", line 141, in __realize
    self.player = ImagePlayer(self)
  File "/home/olpc/Activities/Bichos.activity/CucaraSims/JAMediaImagenes/ImagePlayer.py", line 29, in __init__
    self.player = PlayerBin(self.xid, self.width, self.height)
  File "/home/olpc/Activities/Bichos.activity/CucaraSims/JAMediaImagenes/ImagePlayer.py", line 77, in __init__
    self.video_bin = Video_Out(width, height)
  File "/home/olpc/Activities/Bichos.activity/CucaraSims/JAMediaImagenes/ImagePlayer.py", line 142, in __init__
    width, height))
TypeError: function takes at most 0 arguments (1 given)
Traceback (most recent call last):
  File "/home/olpc/Activities/Bichos.activity/CucaraSims/Widgets.py", line 141, in __realize
    self.player = ImagePlayer(self)
  File "/home/olpc/Activities/Bichos.activity/CucaraSims/JAMediaImagenes/ImagePlayer.py", line 29, in __init__
    self.player = PlayerBin(self.xid, self.width, self.height)
  File "/home/olpc/Activities/Bichos.activity/CucaraSims/JAMediaImagenes/ImagePlayer.py", line 77, in __init__
    self.video_bin = Video_Out(width, height)
  File "/home/olpc/Activities/Bichos.activity/CucaraSims/JAMediaImagenes/ImagePlayer.py", line 142, in __init__
    width, height))
TypeError: function takes at most 0 arguments (1 given)
Traceback (most recent call last):
  File "/home/olpc/Activities/Bichos.activity/CucaraSims/CucaraSims.py", line 123, in __run_lectura
    dialog.stop()
  File "/home/olpc/Activities/Bichos.activity/CucaraSims/Widgets.py", line 69, in stop
    visor.player.stop()
AttributeError: 'bool' object has no attribute 'stop'
```

Needs substantial testing after the port to GTK 3.

**Comment by quozl** [comment]
Was known from the original [pull request](https://github.com/sugarlabs/bichos-activity/pull/5) but @tonadev had not [set up a test environment for GTK 2 and GStreamer 0.10](https://github.com/sugarlabs/sugar-docs/blob/master/src/gtk3-porting-guide.md#how-to-port-a-sugar-activity-to-gtk-3) and nor did anyone else.  :grin:  It's an opportunity.
